# Generated by Django 4.1 on 2023-01-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('razon_social', models.CharField(max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(choices=[('10.5', 10.5), ('21.0', 21.0)], decimal_places=2, default=21.0, max_digits=4)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
