# Generated by Django 4.1 on 2023-02-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0002_proveedores_alter_factura_iva_recibo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='posicion_iva',
            field=models.CharField(choices=[('Responsable Inscripto', 'Responsable Inscripto'), ('Exento', 'Exento'), ('No Responsable', 'No Responsable'), ('No Inscripto', 'No Inscripto')], max_length=50, verbose_name='Posición IVA'),
        ),
    ]
