# Generated by Django 4.1 on 2023-01-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0002_alter_factura_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='comprobantes.factura')),
            ],
        ),
    ]
