# Generated by Django 4.1 on 2023-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_factura_estado_alter_proveedores_posicion_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='posicion_iva',
            field=models.CharField(choices=[('Responsable Inscripto', 'Responsable Inscripto'), ('No Responsable', 'No Responsable'), ('Exento', 'Exento'), ('No Inscripto', 'No Inscripto')], max_length=50, verbose_name='Posición IVA'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='numero',
            field=models.CharField(max_length=15, verbose_name='Número de recibo'),
        ),
    ]
