# Generated by Django 4.1 on 2023-01-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='factura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='comprobantes.factura', verbose_name='Nº Factura'),
        ),
    ]
