# Generated by Django 4.1 on 2023-02-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0004_alter_proveedores_posicion_iva_alter_recibo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=21.0, max_digits=4, verbose_name='% IVA')),
                ('estado', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobantes.categoria')),
            ],
        ),
        migrations.AlterModelOptions(
            name='recibo',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='posicion_iva',
            field=models.CharField(choices=[('Exento', 'Exento'), ('No Inscripto', 'No Inscripto'), ('Responsable Inscripto', 'Responsable Inscripto'), ('No Responsable', 'No Responsable')], max_length=50, verbose_name='Posición IVA'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='factura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='comprobantes.factura', verbose_name='Nº Factura apagar'),
        ),
        migrations.CreateModel(
            name='ReciboCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, verbose_name='Número de recibo de cobro')),
                ('fecha', models.DateField()),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_cobro', to='comprobantes.facturaventa', verbose_name='Nº Factura a Cobrar')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='razon_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobantes.proveedores', verbose_name='Razón Social'),
        ),
    ]
