# Generated by Django 4.1 on 2023-01-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0004_alter_recibo_factura_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='factura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='comprobantes.factura', verbose_name='Nº Factura'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='importe_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
