# Generated by Django 4.1 on 2023-02-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0005_categoria_facturaventa_alter_recibo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='unidades',
            field=models.CharField(blank=True, choices=[('kilos', 'kilos'), ('toneladas', 'toneladas'), ('litros', 'litros')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='posicion_iva',
            field=models.CharField(choices=[('Exento', 'Exento'), ('No Responsable', 'No Responsable'), ('Responsable Inscripto', 'Responsable Inscripto'), ('No Inscripto', 'No Inscripto')], max_length=50, verbose_name='Posición IVA'),
        ),
    ]
