# Generated by Django 4.1 on 2023-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0005_alter_recibo_factura_id_alter_recibo_importe_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Saldada'),
        ),
    ]
