# Generated by Django 4.1 on 2023-02-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0008_rename_importe_pagado_recibocobro_importe_cobrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='posicion_iva',
            field=models.CharField(choices=[('Exento', 'Exento'), ('No Responsable', 'No Responsable'), ('No Inscripto', 'No Inscripto'), ('Responsable Inscripto', 'Responsable Inscripto')], max_length=50, verbose_name='Posición IVA'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='unidades',
            field=models.CharField(blank=True, choices=[('litros', 'litros'), ('kilos', 'kilos'), ('toneladas', 'toneladas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='posicion_iva',
            field=models.CharField(choices=[('Exento', 'Exento'), ('No Responsable', 'No Responsable'), ('No Inscripto', 'No Inscripto'), ('Responsable Inscripto', 'Responsable Inscripto')], max_length=50, verbose_name='Posición IVA'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.CharField(max_length=15),
        ),
    ]
